# path: .config/starship.toml

palette = "catppuccin_macchiato"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[username]
style_user = 'white'
style_root = 'white'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@](white)[$hostname](white) '
disabled = false

[directory]
truncation_length = 1
truncation_symbol = '…/'
truncate_to_repo = false
format = '[󰝰](bold blue) [$path](bold blue) '

[git_branch]
symbol = ' '
truncation_length = 4
truncation_symbol = '…'
format = '[$symbol$branch(:$remote_branch)]($style) '

[package]
disabled = true

[c]
disabled = true

[nodejs]
disabled = true

[helm]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[php]
disabled = true

[terraform]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true 

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
